### ISSUE TITLE
Use Prepared Statements

### ISSUE THREAD

**Issue by matrixdevuk** [kemsly/PHPLogin#1]
You need to use prepared statements buddy! ;)

**Comment by kemsly** [comment]
Ohh, I see. I thought you meant I had to use PDO not mysqli. Although I will change anything in my code using mysql to use prepared statements aswell in a bit.

---- On Sun, 10 May 2015 18:14:50 +0000 Samuel Lewis &lt;notifications@github.com&gt; wrote ---- 

You need to use prepared statements buddy! ;)

**Comment by matrixdevuk** [comment]
MySQLi or PDO works. :)

As long as it's there.

**Comment by kemsly** [comment]
Fixed. I also updated it to use PDO since MySQLI was being buggy with prepared statements. Thanks for the information too!
