### ISSUE TITLE
Remove MD5

### ISSUE THREAD

**Issue by matrixdevuk** [kemsly/PHPLogin#2]
md5(); is a piece of crap.
Get rid of it and put something decent, lol.

**Comment by kemsly** [comment]
I changed it from MD5 to SHA512 now. Although this alg doesn't have salting it's still better than MD5 because its less common. I will soon (Attempt) to update to Bcrypt which has salting, however it will be much more complex.

**Comment by kemsly** [comment]
Update: I added Bcrypt now so it will be about as secure as I can get it(to the extent of my knowledge).
